### ISSUE TITLE
Not compatible with ruby-1.9?

### ISSUE THREAD

**Issue by craig** [darxriggs/ip-world-map#1]
I'm getting this error when run it:

/usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- typhoeus (LoadError)
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/ip-world-map-1.0.0/lib/ip-world-map/ip_lookup_service.rb:2:in `<top (required)>'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/ip-world-map-1.0.0/lib/ip-world-map.rb:3:in`<top (required)>'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib64/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /usr/local/lib64/ruby/gems/1.9.1/gems/ip-world-map-1.0.0/bin/ip-world-map:7:in `<top (required)>'
    from /usr/local/bin/ip-world-map:23:in`load'
    from /usr/local/bin/ip-world-map:23:in `<main>'

**Comment by darxriggs** [comment]
Oh you've find a really old gem. :-)
And yes, I missed to specify the "typhoeus" dependency.
Just released version 1.0.1.
